### ISSUE TITLE
API Key not being checked before transactions posted

### ISSUE THREAD

**Issue by mramage** [MattFaz/actualtap#22]
I have been playing around getting actualtap running, and it seems that the API key either isn't being checked, or I've stuffed up my configuration.

I'm using portainer to manage my docker compose files, and using environment variables.  Here's the section of the compose file that I'm using:
```
  actualtap:
    container_name: actualtap 
    image: mattyfaz/actualtap:latest
    restart: always
    ports:
      - 3001:3001
    volumes:
      - /data/actual-budget/actualtap/data:/app/data
    environment:
      TZ: ${TZ}
      API_KEY: ${API_KEY}
      ACTUAL_URL: ${ACTUAL_URL}
      ACTUAL_PASSWORD: ${ACTUAL_PASSWORD}
      ACTUAL_SYNC_ID: ${ACTUAL_SYNC_ID}
```

If I execute `sudo docker exec <container_ID> env`, it lists the correct API key value `API_KEY=1234abcd-56ef-78ab-90cd-123456abcdef`. I've tried with and without double quotes around the value.

If I run the following curl command without any X-API-KEY header, it adds the transaction successfully

```
$ curl -X POST http://privatehostname:3001/transaction   -H "Content-Type: application/json"   -d '{"account":"My CC", "amount":"1.23","notes":"testing123"}'
{"payee_name":"Unknown","amount":-123,"notes":"testing123","date":"2025-06-29","cleared":false}
```

![Image](https://github.com/user-attachments/assets/a84e4fe4-8a97-4b3a-a861-b64e5f07c92f)
